### PR TITLE
Feature/1200543167522215/org social media icons

### PR DESCRIPTION
**Pull request by ky572**
## Description

Adding social media icons to catalog according to Figma mockup. See Asana ticket for link to mockup.

## PR Checklist

- [x] Assign @FJKhan **and** @Alfredo-Moreira as reviewers.
- [x] If your PR is not a hotfix, is it targeted for `dev`? If it is a hotfix, is it targeted for `master`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [ ] Does the original ticket have test instructions? If not add them below
- [ ] Pass QA Gate(manual testing)

## How to Test

1) In Control Panel, navigate to an organization's page, scroll down the "Social Media" section, and make sure there is at least one social media profile present. If none are present, add one.

2) Visit organization's page in catalog. In desktop view, check that social media icons appear as in the mockup.

3) Verify mobile view by resizing window, visiting from mobile device, or using responsive mode in browser.

4) Try this with different combinations of social media profiles.

### CODE REVIEW

**Review by Alfredo-Moreira — APPROVED** [review]
Was able to verify:
- Adding and removing social media links. 
- Click and being redirected by links
- different views and display of icons in mobile view
Screen Shot 2021-08-19 at 9 57 33 PM
Screen Shot 2021-08-19 at 9 56 54 PM



Note:
- Catalog does allow to set multiple links for one social media platform. But it is out of scope for this story

**Comment by ky572** [comment]
@Alfredo-Moreira Are you seeing black icons in the mobile view? They are supposed to be blue, and this is what I see:

image

Also I discussed with FJ yesterday and subsequently reached out to Abby about what to do with organizations that have multiple links for the same social media platform. If this PR is okay as is, I supposed we can create another ticket for if/when she and the other resource coordinators achieve consensus on this requirement.

**Comment by FJKhan** [comment]
@ky572 the black icon is a glitch that occurs when you switch the chrome dev tools viewport from desktop to mobile. refreshing the page shows the correct styles. also, we spoke about some code changes day (awaiting those), and yes, we can create another ticket for the multiple social media links for a single platform issue.

> @Alfredo-Moreira Are you seeing black icons in the mobile view? They are supposed to be blue, and this is what I see:
> 
> image
> 
> Also I discussed with FJ yesterday and subsequently reached out to Abby about what to do with organizations that have multiple links for the same social media platform. If this PR is okay as is, I supposed we can create another ticket for if/when she and the other resource coordinators achieve consensus on this requirement.

**Comment by ky572** [comment]
@FJKhan changes are in

**Comment by Alfredo-Moreira** [comment]
I did some more testing. Here is what I found:

Control Panel does not make any validation on adding social media links. You can add a link without specifying the platform or input a bad URL:
Screen Shot 2021-08-30 at 10 32 36 PM

This causes the catalog to crash(blank page ) when trying to load the Org Page:

Screen Shot 2021-08-30 at 10 40 11 PM

When URL has a platform but bad URL:
Screen Shot 2021-08-30 at 10 45 49 PM

It causes the Catalog to display something weird when the link is clicked:
Screen Shot 2021-08-30 at 10 42 53 PM


Org used: nebraska-aids-project if you want to replicate my findings.

**Comment by FJKhan** [comment]
@Alfredo-Moreira awesome. thanks!
the lack of validation is a control panel problem (not in scope for this task) and the url which results when the provided url doesn't have a protocol is expected React behaviour. it's assuming that the link is internal to the application. are we good otherwise? will try to get the validation in shortly.

**Comment by ky572** [comment]
@FJKhan do you want to open a ticket for social media validation on the control panel? Abby confirmed that we should only have maximum one profile per platform as well. 

Additionally, I think we should keep the socialMediaPlatforms array. It ensures that the icons render in a consistent order, regardless of the order the profiles were saved in the db. The story's AC was not explicit about the order, but I thought keeping it consistent based on the mockup (FB - Twitter - Instagram) would be good UX. Unless some profiles are considered "primary" and others "secondary" or something like that. In that case, I could understand changing the order up based on the data, but would then suggest adding additional fields to the social media objects, but I don't see any indication that that's a requirement. An added benefit is that it is an added layer of protection against the first problem from above with the blank string, since the app would look only for platforms that it supported (e.g. had icon mappings for).

**Comment by Alfredo-Moreira** [comment]
> @Alfredo-Moreira awesome. thanks!
> the lack of validation is a control panel problem (not in scope for this task) and the url which results when the provided url doesn't have a protocol is expected React behaviour. it's assuming that the link is internal to the application. are we good otherwise? will try to get the validation in shortly.

Yes otherwise we are good. The feature works as expected when the URL is entered correctly.

**Comment by FJKhan** [comment]
@ky572  here's the [social media validation ticket](https://app.asana.com/0/1132189118126148/1200881468845263/f). lmk if you want to tackle it.
we can sort the array in alphabetical order. the mockups aren't set in stone and that's the easiest way to ensure consistent ordering. will do a patch for this later this week.

**Pull request merged**
