### PR TITLE
More automation Favorites Feature

### PR DESCRIPTION
**Pull request by Alfredo-Moreira**
## PR Checklist

- [ ] Assign @FJKhan **and** @Alfredo-Moreira as reviewers.
- [ ] If your PR is not a hotfix, is it targeted for `dev`? If it is a hotfix, is it targeted for `master`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [ ] Does the original ticket have test instructions? If not add them below
- [ ] Pass QA Gate(manual testing)

### CODE REVIEW

**Comment by FJKhan** [comment]
several of the favourites feature tests are failing:

image

**Comment by Alfredo-Moreira** [comment]
> several of the favourites feature tests are failing:
> 
> image

Checking them out now

**Comment by Alfredo-Moreira** [comment]
Re-ran the tests and they were all fine. Locally and on Circle

**Comment by FJKhan** [comment]
so odd.

**Pull request merged**
