### PR TITLE
Feature/1200183167048184/search by name

### PR DESCRIPTION
**Pull request by FJKhan**
## Description

- adds ability to search the catalog by organization name

## PR Checklist

- [ ] Assign @FJKhan **and** @Alfredo-Moreira as reviewers.
- [x] If your PR is not a hotfix, is it targeted for `dev`? If it is a hotfix, is it targeted for `main`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [ ] Does the original ticket have test instructions? If not add them below
- [ ] Pass QA Gate(manual testing)

### CODE REVIEW

**Review by Alfredo-Moreira — CHANGES_REQUESTED** [review]
I tested the deployed URL: https://reviews-catalog-pr-170.herokuapp.com/ 
I tried both states(logged in and not logged in).
Both scenarios resulted in the same behavior:

- After clicking on find organization by name does not load anything. See screenshots below.

Screen Shot 2021-08-26 at 7 41 18 AM
Screen Shot 2021-08-26 at 7 41 30 AM

**Review by Alfredo-Moreira — CHANGES_REQUESTED** [review]
Testing again i found 2 things:

- Looks like the auto-population is working correctly. Although when you select the item in auto-populate it does nothing but completing the auto-populate. Is it supposed to trigger the search or just complete the auto-populate?
- Once you click the organization and click search, It seems like it is doing the search including the exact match as well as regex matches. What is the sort order being used?

If these are not issues then it is approved.

**Comment by FJKhan** [comment]
Awesome sauce. Thank you!
To respond to your notes:

1. The search by name input field should only auto-populate the field. The user still has to click the "search" button to trigger the search.

2. The search does indeed do exact/regex matching. It sorts using the highest MongoDB "match" score, which may or may not be the search query

> Testing again i found 2 things:
> 
> * Looks like the auto-population is working correctly. Although when you select the item in auto-populate it does nothing but completing the auto-populate. Is it supposed to trigger the search or just complete the auto-populate?
> * Once you click the organization and click search, It seems like it is doing the search including the exact match as well as regex matches. What is the sort order being used?
> 
> If these are not issues then it is approved.

**Review by Alfredo-Moreira — APPROVED** [review]
Approved latest changes.

**Pull request merged**
